var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/welcome/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__785d20ed._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/_45346f30._.js")
R.c("server/chunks/ssr/[root-of-the-server]__ae8686ec._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0d5ae7ad._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__2879ce30._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_welcome_page_actions_e32fb27e.js")
R.m(88170)
module.exports=R.m(88170).exports
