export interface BlogPost {
  slug: string;
  title: string;
  date: string;
  description: string;
  readingTime: string;
  content: string;
}

export const posts: BlogPost[] = [
  {
    slug: "why-i-built-clawdoctor",
    title: "Why I Built ClawDoctor: A Self-Healing Monitor for Local AI Gateways",
    date: "2026-03-15",
    description:
      "The story of how a 3am gateway crash on a production AI pipeline led to building a self-healing monitor for OpenClaw.",
    readingTime: "4 min read",
    content: `I run twenty-something OpenClaw agents in production.

Not a side project. Not a toy. These agents generate content, process customer data, and drive revenue. When they break, money stops moving and customers notice.

For the first six months, I dealt with failures the way most people do: I found out from a user, or I woke up to a notification that something downstream had gone quiet. I would SSH in, grep logs, figure out that the gateway had died two hours ago, restart it, and go back to sleep. Every time I told myself I'd set up proper monitoring. Every time, something more urgent came up.

**The night that changed it**

It was a Tuesday, around 3am. I got a message from a client: "the daily briefing didn't arrive." That briefing was generated by a cron job that ran at midnight, posted results through an OpenClaw session, and delivered via webhook. Somewhere in that chain, the gateway had silently died at 11:58pm — two minutes before the cron fired.

The cron ran. It connected to localhost:8080. It got a connection refused. It exited with code 0 because the error handling was too lenient. No alert fired. No log was written. The cron technically "succeeded."

I restarted the gateway, re-ran the job, delivered the briefing with an apology. Four hours of silence. I had been asleep.

That was the moment I decided to stop tolerating it.

**What I wanted didn't exist**

I looked around for tools that could watch OpenClaw specifically. Sentry handles errors in application code. Langfuse handles LLM call tracing. Uptime monitors handle HTTP endpoints. None of them understood OpenClaw's state files, session structure, or cron delivery model. None of them knew how to look at an OpenClaw gateway and say: this restarted three times in the last hour, something is wrong.

I didn't want a generic monitoring dashboard with fifty knobs to configure. I wanted something opinionated: a process that understood OpenClaw and knew what "healthy" looked like, without me having to teach it from scratch.

**Building the first version**

The first version was a Node script I ran in a tmux session. It polled the OpenClaw process table every sixty seconds, checked the gateway port, read the session logs. If the gateway was down, it ran \`openclaw gateway restart\` and sent me a Telegram message.

That alone saved me probably three incidents in the first two weeks.

Then I added cron watching. OpenClaw cron jobs write delivery receipts — or they're supposed to. If a receipt is missing, ClawDoctor flags it. If it's stale, ClawDoctor flags it. You get a message that says: "writer-content-drafts last delivery was 26 hours ago, expected every 24h."

Then session watching. Sessions that run more than 3x their baseline duration. Sessions that emit repeated errors. Sessions that start and never finish.

Then cost watching. A runaway session burning $40 in a loop is not a hypothetical — it has happened to me, and I caught it too late.

**Where it is now**

ClawDoctor is a proper daemon now. It starts on boot, runs five watchers on configurable intervals, and maintains a local event log. The free tier covers the core watchers. Paid tiers add pattern matching, multi-channel alerts, and — in v2 — actual auto-fix actions: token refresh, config repair, approval flows via Telegram before taking any risky action.

The auto-restart feature has been running in production for four months. In that time, it has restarted my gateway eleven times. I noticed zero of those restarts while they were happening.

**Who this is for**

If you're running one OpenClaw agent locally, you probably don't need ClawDoctor yet. When it breaks, you'll notice immediately.

If you're running several agents, crons, and sessions — in production, for paying customers, overnight — you need something watching the watcher. That's what ClawDoctor is.

It's open source. The core is free. Install it in sixty seconds with \`npm install -g clawdoctor && clawdoctor init\`.

The 3am gateway crash that started this: it hasn't happened undetected since.`,
  },
];

export function getPost(slug: string): BlogPost | undefined {
  return posts.find((p) => p.slug === slug);
}
